### PR TITLE
Support CDATA gracefully

### PR DESCRIPTION
**Pull request by qixin1991**
Hello,i'm from China and developing a trade system. This system needs to use `wechat pay` (wechat is the most popular IM App in China). 

The pay API using `xml` and `json` to connect third party development system. And `CDATA` was used heavily. So i forked `node-xml2js` and add a new way to support `CDATA`.

If you think this `PR` can be useful. Please accept.

Thanks!

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
Except for removing all kinds of CI information, contributor info, what does this PR improve?

**Comment by qixin1991** [comment]
@Leonidas-from-XIV Sorry for that,it's my mistake. Few days ago,before PR was accepted,i want to publish into npm website,however it failed. So i try to delete something.
This PR improve `CDATA` usage. For example:

Screenshot1
image

Screenshot2
image

Can you hear me? 😅

**Comment by qixin1991** [comment]
Well, the real PR content is  [`src/builder.coffee` at the bottom](https://github.com/Leonidas-from-XIV/node-xml2js/pull/375/commits/21702dcf6db9621869ff3f207bc563efbc58e3cd)

**Comment by Leonidas-from-XIV** [comment]
This PR is unusable in this form, closing.

**Pull request closed without merging**
