### PR TITLE
Added new dependency to package.json to support React-Native usage

### PR DESCRIPTION
**Pull request by franrios**

### CODE REVIEW

**Comment by rubengarciam** [comment]
Has this pull been fully merged? I'm trying to use it but still is fails as if it wasn't a valid _react-native_ package.

Neither _xml2js_ nor _react-native-xml2js_ via _npm_

**Comment by franrios** [comment]
It's not merged yet. The only change that I did in this PR is adding a dependency that enable this package to be used in a react-native project.

**Comment by xsc** [comment]
So, I just stumbled upon this, but to me it seems that this PR should be opened at [connected-lab/react-native-xml2js](https://github.com/connected-lab/react-native-xml2js) which is the repository referenced by the NPM package.

Which, of course, means that it should be closed here.

**Comment by franrios** [comment]
You are right. I'll close it then

**Comment by franrios** [comment]
You are right. I'll close it then.

**Comment by hkar19** [comment]
i think this PR should be here as the [connected-lab/react-native-xml2js](https://github.com/connected-lab/react-native-xml2js) is archived.

and it is only one dependency that this package assume it was just there.

If this could not be merged, we should update this repo doc to say:
> "In order to use this repo in RN, you should install `timer` yada yada"

**Pull request closed without merging**
