### PR TITLE
Follow XML 1.1 spec for valid chars instead of 1.0

### PR DESCRIPTION
**Pull request by adrai**
fixes: https://github.com/oozcitak/xmlbuilder-js/issues/154

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
Could you set it as range, similarly to before?

**Comment by adrai** [comment]
>=9.0.1   ok?
Because it must be at least 9.0.1

**Comment by adrai** [comment]
'>=9.0.1'

**Comment by adrai** [comment]
Any ETA for a new release?

**Comment by Leonidas-from-XIV** [comment]
There hasn't been one in quite some time indeed, so I've just pushed a new release.

**Pull request merged**
