### PR TITLE
Added bower.json

### PR DESCRIPTION
**Pull request by tflanagan**
Added bower.json, please verify that these settings are correct.

Bower is a first come, first serve in terms of package ownership.

@Leonidas-from-XIV, let's make sure you own this package.

http://bower.io/docs/creating-packages/#register

Notes on bower.json configuration:
https://github.com/bower/spec/blob/master/json.md

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
It would be nice if there was a way to synchronize `bower.json` from `package.json`…

**Comment by tflanagan** [comment]
It would be.

We could write a simple npm script that does this?

**Comment by Leonidas-from-XIV** [comment]
Yeah, that'd be neat. I found [grunt-sync-json](https://www.npmjs.com/package/grunt-sync-json), [grunt-npm2bower-sync](https://www.npmjs.com/package/gulp-config-sync) [grunt-update-json](https://www.npmjs.com/package/grunt-update-json) [gulp-config-sync](https://www.npmjs.com/package/gulp-config-sync), but pulling in a build system for this is kinda ridiculous.

**Comment by tflanagan** [comment]
It really is...

I can't imagine `bower.json` will need to be changed too frequently. Bower supposedly uses GitHub tags for version tracking. The only time this file would be updated is for dep updates (which are linked via GitHub, so only Coffee-Script would need updating), or author updates.

I can't see a build system like that being worth it. The 10 seconds of manual synchronizing isn't that bad.

**Comment by tflanagan** [comment]
Which, by the way, you are missing the v0.4.13 tag/release

**Comment by tflanagan** [comment]
According to https://github.com/bower/spec/blob/master/json.md#version you do not need to supply a version in ```bower.json```

**Comment by Leonidas-from-XIV** [comment]
Sorry I was being unclear, I meant "every version bump of a dependency".

**Comment by tflanagan** [comment]
Even then, using git for everything but Coffee-Script seems to make this file nearly self-maintaining.

This will be a first, using Grunt/Gulp. I have no preference. Do you? Those packages you linked above all seem to do the job nicely.

**Comment by Leonidas-from-XIV** [comment]
Truth be told I don't want either. Just a shellscript or something that can be called and handles it would be more than enough. I wonder if there is a tool that does something like XSLT for JSON.

**Comment by tflanagan** [comment]
Haha, we could.

I was thinking of a basic script too - Eventually, if these deps get on bower, we should use those packages instead of git. ```bower lookup <name>``` could be hooked into said script.

**Pull request merged**
