### PR TITLE
Added parseBooleans

### PR DESCRIPTION
**Pull request by cressie176**

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
You forgot to run `cake build`, so the JS files do not reflect your changes and Travis fails to build it.

**Comment by cressie176** [comment]
From CONTRIBUTING.md

> Please don't send patches to the JavaScript source, as it get's overwritten by the CoffeeScript compiler. 

However I'll do as you suggest. I also forgot to update the README so will do that too

**Comment by Leonidas-from-XIV** [comment]
This means that you should not ONLY patch the JS. I've gotten such PRs as well.

**Comment by cressie176** [comment]
Hold off on the PR - just put similar code into my app and getting an error

**Comment by cressie176** [comment]
False alarm. All good from my site

**Comment by x3ro** [comment]
:+1:

**Comment by Leonidas-from-XIV** [comment]
Sure, why not.

**Pull request merged**
