### PR TITLE
extend explicitArray options as a key array for the xml support named array really

### PR DESCRIPTION
**Pull request by yujunlong2000**

### CODE REVIEW

**Comment by adamr2** [comment]
This is very useful and elegant.
Why is this not being merged?

**Comment by Leonidas-from-XIV** [comment]
Because I think explicitArray should be always default to produce an object with an obvious structure, and not be extended to have options so the tree that is output gets even more unpredictable.

**Comment by adamr2** [comment]
IMHO, this does give predictable output (since we can define the keys) and also better control over the output.
Specifically, I'm converting xml\json back and forth in my application and I don't want to pollute my jsons with explicit arrays for every field.

**Comment by Leonidas-from-XIV** [comment]
You can easily do such a thing as a postprocessing step (unlike the opposite direction), no need to push such auxillary logic into this library.

**Pull request closed without merging**
