### PR TITLE
Add promise-specific version of parseString

### PR DESCRIPTION
**Pull request by mckramer**
A possible solution for #421.  Due to the "async" option, it did not seem possible to convert the existing implementation, so, instead, use [util.promisify](https://nodejs.org/api/util.html#util_util_promisify_original) (via [shim](https://github.com/ljharb/util.promisify/) to support node < 8).

Examples:

```js
// Via root API
xml2js.parseStringPromise('< ... >', options)
  .then(function (result) { /* ... */ })
  .catch(function (err) { /* ... */ })

// Via parser
var parser = new xml2js.Parser(options);
parser.parseStringPromise('< ... >')
  .then(function (result) { /* ... */ })
  .catch(function (err) { /* ... */ })
```

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
It fails on all CI environments :-(

**Comment by mckramer** [comment]
@Leonidas-from-XIV, I did not realize I needed to commit the compiled JS as well.  I did that now.  This PR fails on node 0.10 + 0.12.  As those are EOL, do you want to keep supporting them?  I also opened #430 in case you wanted to consider dropping support for EOL versions.

**Comment by Leonidas-from-XIV** [comment]
@mckramer Yeah, the files are there to lower the amount of dependencies required to use the project. This was before compiling was super-popular in JS. For now they are there, when I re-do things I'll think of some better solution since no-one likes generated files in the repository anyway 😄 

If you rebase your branch onto master you should get more recent version of Node 👍

**Comment by Leonidas-from-XIV** [comment]
I just thought of something: maybe it is ok if `parseString` returned a promise if no callback was passed? That way there is no additional function. The downside is that `parseString` will have very confusing behaviour.

**Comment by j3k0** [comment]
> maybe it is ok if parseString returned a promise if no callback was passed

Maybe it could even __always__ return a Promise, regardless of the callback argument. So far, `parseString` doesn't have a defined returned value.

**Comment by Leonidas-from-XIV** [comment]
Yes, this is *way* better, also makes the typing less surprising.

**Comment by mckramer** [comment]
Sorry for delay in coming back to this.

I was not able to find a way to make the promise returnable always without breaking the existing API in some way.  @j3k0 mentioned it in #441, but there are unit tests that rely on sync exceptions and returns (and some odd behavior with the "async" option return).  Maybe you can consider those unit tests not an intended API, but it is technically breaking, which is why I opted to create a separate `parseStringPromise` method.

Either way would be fine with me, but I do think that if you go always return promise (i.e. #441), you should bump the "major" version and note the change, in case anyone is relying on the existing behavior.

**Comment by miguel-orange** [comment]
@mckramer - Thanks for putting this PR together.

**Comment by buphmin** [comment]
If anyone is interested in the meantime here is a typescript example of how you can write your own wrapper with @types/xml2js.

``` typescript
import {convertableToString, OptionsV2, parseString} from 'xml2js';

function parseStringAsync(xml: convertableToString, options?: OptionsV2): Promise<any> {
  return new Promise((resolve, reject) => {
    if(options) {
      parseString(xml, (err, results) => {
        if(err) {
          reject(err);
        }

        resolve(results);
      });
    } else {
      parseString(xml, options, (err, results) => {
        if(err) {
          reject(err);
        }

        resolve(results);
      });
    }
  })
}
```

**Comment by alexkb** [comment]
@buphmin thanks for sharing your snippet. You may want to swap the if statement blocks around though, as currently it won't pass the options parameter to `parseString()`.

**Comment by bradleat** [comment]
+1

**Comment by yunfan** [comment]
> If anyone is interested in the meantime here is a typescript example of how you can write your own wrapper with @types/xml2js.
> 
> ```ts
> import {convertableToString, OptionsV2, parseString} from 'xml2js';
> 
> function parseStringAsync(xml: convertableToString, options?: OptionsV2): Promise<any> {
>   return new Promise((resolve, reject) => {
>     if(options) {
>       parseString(xml, (err, results) => {
>         if(err) {
>           reject(err);
>         }
> 
>         resolve(results);
>       });
>     } else {
>       parseString(xml, options, (err, results) => {
>         if(err) {
>           reject(err);
>         }
> 
>         resolve(results);
>       });
>     }
>   })
> }
> ```

thanks for the helpful fix, but there is a Logical reverse in the code.

**Comment by knoxcard** [comment]
@mckramer - nice job!

**Comment by Leonidas-from-XIV** [comment]
It didn't close the PR automatically but rest assured I just merged @mckramer's changes into master.

**Pull request closed without merging**
