### PR TITLE
adding parseStringSync + simple tests (continued)

### PR DESCRIPTION
**Pull request by mrparkers**
Apologies for getting this in so late, I haven't had the free time to work on this until now.

This PR is to address the comments made by @Leonidas-from-XIV in #241.  Please refer to that PR for more context around these changes.

I'm pretty sure I got everything, except I was a bit confused by the [comment](https://github.com/Leonidas-from-XIV/node-xml2js/pull/241#discussion_r41654882) asking for `parseStringSync` to adhere to the API of `parseString`.  If that could get cleared up for me, I can take a stab at that as well.

Thanks!

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
@Mrparkers About that comment: the `parseStringSync` function does not accept an (optional) argument map, hence has no way to configure the numerous options that `xml2js` has. I would wish this to be possibly and certainly all future users of that API as well.

**Comment by Mrparkers** [comment]
Okay, I will try to address this when I have some free time.  Thanks!

**Comment by mckramer** [comment]
Rebased these changes and added support for options in #422

**Comment by mrparkers** [comment]
Thanks @mckramer, I'll close this in favor of your PR.  I haven't needed this for quite some time now.

**Pull request closed without merging**
