### PR TITLE
Building Object values that are strings escape to CDATA

### PR DESCRIPTION
**Pull request by jesstelford**
Fixes Leonidas-from-XIV/node-xml2js#178
Refs Leonidas-from-XIV/node-xml2js#171

### CODE REVIEW

**Comment by joshgillies** [comment]
Excellent :+1:

**Comment by Leonidas-from-XIV** [comment]
Thanks, merged & will be part of next release.

**Comment by joshgillies** [comment]
@Leonidas-from-XIV any idea when the next release will be? Very keen for this to land.

**Comment by Leonidas-from-XIV** [comment]
I'd wait for a bit, if anyone comes up with some bugs and if not, release it as a no-new-features-bugfix release. I'm leaving for a conference, so how about next Monday?

**Comment by joshgillies** [comment]
No problems :+1:

**Pull request merged**
