### PR TITLE
fix missing onend function

### PR DESCRIPTION
**Pull request by tflanagan**
This fixes issue #245.

Edit: Whoops, forgot to update my local copy with newest master commits, rebased/amended/pushed. My bad.

### CODE REVIEW

**Comment by tflanagan** [comment]
The merge conflict seems to be in the test I've added. Not sure why...

**Comment by Leonidas-from-XIV** [comment]
I wrote you a small comment but apart from that LGTM! Thanks!

**Comment by tflanagan** [comment]
Sorry, habitual ASI.

Fixed, rather than pollute commit history I've just amended and forced pushed

**Comment by Leonidas-from-XIV** [comment]
Sure, that's completely fine :-) I should make a release soon with the accumulated bugfixes.

**Pull request merged**
