### PR TITLE
added configuration to allow preservation of child node ordering

### PR DESCRIPTION
**Pull request by ryedin**
This might not be what you had in mind, but it offers a configuration option to be able to iterate children in the order they appear in the XML.

Addresses https://github.com/Leonidas-from-XIV/node-xml2js/issues/31

### CODE REVIEW

**Comment by ryedin** [comment]
Let me know if there are any changes needed. I think it slightly modifies behavior of text nodes. Since all nodes now retain the `#name` property (for obvious reasons), there is never a case where a node will look like `[<string>]` -- they will always instead have the text stored in the `_` field.

**Comment by ryedin** [comment]
I just modified the PR with a commit that will retain the behavior of the named (unordered) fields (removes the `#name` property and collapses text-only nodes at that level). The nodes in the children array still always have the `#name` property and thus text will always be in the `_` or charkey field.

**Comment by Leonidas-from-XIV** [comment]
From having a quick look at the code (I don't have much time at the moment) it looks fine. I'll try to have a better look at it during the weekend (and will release 0.4.7 today with the current state so if problems occur, there is a release to roll back to), but if I forget it, please poke me again.

**Comment by ryedin** [comment]
poke.

I updated to fix merge conflict in package.json (contrib section) + added support for preserving the ordering of text nodes with markup inside.

**Comment by ryedin** [comment]
sooo... hey man, not trying to be a pest, but it's been a couple weeks. I already have a project in production now depending on this patch (pointing to my fork). I'm not saying that's reason on its own to merit the merge, just wondering where we stand on this. It would be nice to get back to pointing to your maintained repo and I know you have a lot of followers looking for an option in regard to this issue. 

I'm happy to make any changes you desire, just let me know!

**Comment by Leonidas-from-XIV** [comment]
I'm currently in the final two weeks of finishing my thesis, so haven't yet had time to properly look at this, sorry! It'll definitely be the first PR I look at when I find the time. I really appreciate your effort!

**Comment by ryedin** [comment]
No worries man. Thanks for taking the time to do the merge and to maintain this project in general!

Good luck on the thesis!

**Pull request merged**
