### PR TITLE
sax, xmlbuilder - dependency version bump

### PR DESCRIPTION
**Pull request by knoxcard**
sax and xmlbuilder version bump

### CODE REVIEW

**Comment by ajssd** [comment]
+1 -- please accept these changes

**Comment by Leonidas-from-XIV** [comment]
What is the value of raising the minimum version?

**Comment by ajssd** [comment]
I'm sure it's different for different people, but I work for a big company with a legal department that wants assurance that any 3rd party libraries that we use are actively maintained -- which (to them) means releasing at least every 18-24 months, and being sure that dependencies are similarly up-to-date.  If a 3rd party library is not updated every 18-24 months, they consider it "abandoned" and then we have to go through a big process where we have to assure legal & security people that we will be responsible for any issues that may arise.
So even if you don't make any code changes, you could do a release that merely bumps the dependency versions -- that would be enough.
-Andy



    On Thursday, August 29, 2019, 9:03:34 AM PDT, Marek Kubica <notifications@github.com> wrote:  
 
 
What is the value of raising the minimum version?

**Comment by knoxcard** [comment]
@ajssd - couldn't have said it better myself.

**Comment by knoxcard** [comment]
Only thing failing with Travis is nodejs 4, get rid of it, it's ancient history...

https://travis-ci.org/Leonidas-from-XIV/node-xml2js/builds/578550728?utm_source=github_status&utm_medium=notification

**Comment by knoxcard** [comment]
Woohoo! it passed

**Comment by Leonidas-from-XIV** [comment]
@ajssd But you do realize that this is completely nonsensical? If just by pushing some files around and creating releases I can make this library seem maintained to your legal department that does make no sense. As you see I do very minimal maintenance (since I don't use the library or Node for that matter myself) so even if I did releases bumping minimal dependency versions it would not change the fact that there is very little maintenance actually happening - the concern that your legal department has is still there, just hidden.

It might be even worse if I were to actually audit the dependencies and their dependencies (not that I actually do), since then just bumping the version might move you from an audited version to one that contains malware (and we have seen this happen in npm!).

Also, what about mature libraries? Many small libraries are sort of "done", no need to bump dependency versions if there are no dependencies and the desired functionality is implemented.

**Comment by knoxcard** [comment]
YES SIRR!!!!!!!!!!!!!

**Comment by knoxcard** [comment]
@Leonidas-from-XIV - true.  The malware thing could indeed be detrimental.  Although, in this particular case, SAX and Xmlbuilder are two incredibly ppopular repositories, such as xml2js.

https://www.npmjs.com/package/xmlbuilder (6,628,868 weekly downloads)
https://www.npmjs.com/package/sax (13,127,737 weekly downloads)

The way I personally see it, the more popular/important the repository, the less likely that contributors will be malicious.  Case and point with you, you are concerned about this repository because it is super critical. 5,000,000+ downloads weekly. 

https://www.npmjs.com/package/xml2js (5,424,816 weekly downloads)

**Comment by knoxcard** [comment]
I see everything I mentioned here has been merged, updated and two version changes in the last few days. My work here is complete!

**Pull request closed without merging**
